quarkus.log.level=INFO
quarkus.log.category."info.touret.musicstore".level=DEBUG

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization,X-Requested-With,X-User
go-feature-flag.url=http://localhost:1031
go-feature-flag.polling-interval=10000
quarkus.compose.devservices.files=src/main/docker/compose-devservices.yml
quarkus.application.name=music-store
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.datasource.jdbc.telemetry=true
