welcome-message:
  variations:
    on: true
    off: false
  targeting:
    - query: clientEmail ew "@musician.com"
      variation: on
  defaultRule:
    progressiveRollout:
      initial:
        variation: on
        percentage: 0
        date: 2026-04-28T05:00:00.100Z
      end:
        variation: on
        percentage: 100
        date: 2026-04-28T23:00:00.100Z

discount-enabled:
  variations:
    on: true
    off: false
  targeting:
    - query: clientCountry in ["FRANCE", "GERMANY", "UK"] and clientEmail ew "musician.com"
      progressiveRollout:
        initial:
          variation: on
          percentage: 20
          date: 2026-04-28T05:00:00.100Z
        end:
          variation: on
          percentage: 80
          date: 2026-04-28T23:00:00.100Z
  defaultRule:
    variation: off

discount-amount:
  variations:
    10-percent: 0.1
    20-percent: 0.2
    50-percent: 0.5
  targeting:
    - query: clientCountry eq "GERMANY"
      variation: 50-percent
    - query: clientCountry eq "UK"
      variation: 20-percent
  defaultRule:
    variation: 10-percent
