welcome-message:
  variations:
    on: true
    off: false
  defaultRule:
    variation: on

discount-enabled:
  variations:
    on: true
    off: false
  targeting:
    - query: clientCountry in ["FRANCE", "GERMANY", "UK"]
      variation: on
  defaultRule:
    variation: off

discount-amount:
  variations:
    10-percent: 0.1
    20-percent: 0.2
    50-percent: 0.5
  targeting:
    - query: clientCountry eq "GERMANY"
      variation: 50-percent
    - query: clientCountry eq "UK"
      variation: 20-percent
  defaultRule:
    variation: 10-percent
