services:
  go-feature-flag:
    image: gofeatureflag/go-feature-flag:trixie
    ports:
      - "1031:1031"
    volumes:
      - ./go-feature-flag/flags.yaml:/goff/flags.yaml
      - ./go-feature-flag/proxy.yaml:/goff/goff-proxy.yaml
    environment:
      - POLLING_INTERVAL=1000
