package info.touret.musicstore.application.resource;

import info.touret.musicstore.application.data.OrderDto;
import info.touret.musicstore.application.mapper.OrderMapper;
import info.touret.musicstore.domain.service.OrderService;
import jakarta.inject.Inject;
import jakarta.validation.constraints.NotNull;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import org.eclipse.microprofile.openapi.annotations.Operation;
import org.eclipse.microprofile.openapi.annotations.media.Content;
import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.eclipse.microprofile.openapi.annotations.parameters.RequestBody;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.jboss.resteasy.reactive.ResponseStatus;
import org.jboss.resteasy.reactive.RestPath;

import java.util.List;
import java.util.Map;

/// REST resource for managing music store orders.
/// Provides endpoints for creating, retrieving, updating, and deleting orders.
/// All operations are orchestrated through the OrderService domain service,
/// ensuring business logic remains encapsulated in the domain layer.
@Path("/orders")
public class OrderResource {

    private final OrderMapper orderMapper;
    private final OrderService orderService;

    @Inject
    public OrderResource(OrderMapper orderMapper, OrderService orderService) {
        this.orderMapper = orderMapper;
        this.orderService = orderService;
    }

    /// Retrieve all orders.
    ///
    /// @return a list of all orders in the system
    /// @response 200 Orders retrieved successfully
    /// @response 500 Internal server error
    @Operation(summary = "Retrieve all orders", description = "Retrieve all orders from the music store")
    @APIResponse(responseCode = "200", description = "Orders retrieved successfully")
    @APIResponse(responseCode = "500", description = "Internal server error")
    @GET
    public List<OrderDto> retrieveOrders() {
        return orderMapper.toOrderDtos(orderService.findOrders());
    }

    /// Retrieve a specific order by its ID.
    ///
    /// @param id the unique identifier of the order
    /// @return the order data
    /// @response 200 Order retrieved successfully
    /// @response 404 Order not found
    /// @response 500 Internal server error
    @Operation(summary = "Retrieve an order by ID", description = "Retrieve a specific order using its unique identifier")
    @APIResponse(responseCode = "200", description = "Order retrieved successfully")
    @APIResponse(responseCode = "404", description = "Order not found")
    @APIResponse(responseCode = "500", description = "Internal server error")
    @GET
    @Path("/{id}")
    public OrderDto retrieveOrder(@NotNull @RestPath("id") Long id) {
        return orderMapper.toOrderDto(orderService.findById(id));
    }

    /// Create a new order.
    /// The order ID must be null (will be generated by the system).
    ///
    /// @param orderDto the order data (without an ID)
    /// @return a response containing the generated order reference
    /// @response 201 Order created successfully
    /// @response 400 Invalid request body or order ID is not null
    /// @response 500 Internal server error
    @Operation(summary = "Create a new order", description = "Create a new order in the music store")
    @APIResponse(responseCode = "201", description = "Order created successfully")
    @APIResponse(responseCode = "400", description = "Invalid request body")
    @APIResponse(responseCode = "500", description = "Internal server error")
    @POST
    @ResponseStatus(201)
    public Map<String, String> createOrder(@NotNull OrderDto orderDto) {
        return Map.of("id", orderService.createOrder(orderMapper.toOrder(orderDto)).reference().toString());
    }

    /// Update an existing order.
    /// The order ID in the path must match the ID in the request body.
    ///
    /// @param id       the unique identifier of the order to update
    /// @param orderDto the updated order data
    /// @return the updated order
    /// @response 200 Order updated successfully
    /// @response 400 Order ID mismatch or invalid request
    /// @response 404 Order not found
    /// @response 500 Internal server error
    @Operation(summary = "Update an order", description = "Update an existing order using its unique identifier")
    @APIResponse(responseCode = "200", description = "Order updated successfully")
    @APIResponse(responseCode = "400", description = "Order ID mismatch")
    @APIResponse(responseCode = "404", description = "Order not found")
    @APIResponse(responseCode = "500", description = "Internal server error")
    @PUT
    @Path("/{id}")
    public OrderDto updateOrder(@NotNull @RestPath("id") Long id,
                                @NotNull @RequestBody(required = true,
                                        content = @Content(mediaType = MediaType.APPLICATION_JSON,
                                                schema = @Schema(implementation = OrderDto.class))) OrderDto orderDto) {
        if (!orderDto.id().equals(id)) {
            throw new IllegalArgumentException(String.format("Order id %s does not match %s", id, orderDto.id()));
        }
        return orderMapper.toOrderDto(orderService.updateOrder(orderMapper.toOrder(orderDto)));
    }

    /// Delete an order.
    ///
    /// @param orderId the unique identifier of the order to delete
    /// @response 204 Order deleted successfully
    /// @response 404 Order not found
    /// @response 500 Internal server error
    @Operation(summary = "Delete an order", description = "Delete an order from the music store")
    @APIResponse(responseCode = "204", description = "Order deleted successfully")
    @APIResponse(responseCode = "404", description = "Order not found")
    @APIResponse(responseCode = "500", description = "Internal server error")
    @DELETE
    @Path("/{id}")
    public void deleteOrder(@NotNull @RestPath("id") String orderId) {
        orderService.deleteOrder(orderService.findById(Long.valueOf(orderId)));
    }

    /// Search for orders by query string.
    ///
    /// @param query the search query (non-empty)
    /// @return a list of matching orders
    /// @response 200 Orders searched successfully
    /// @response 400 Invalid or empty query
    /// @response 500 Internal server error
    @Operation(summary = "Search orders", description = "Search for orders using a query string")
    @APIResponse(responseCode = "200", description = "Orders searched successfully")
    @APIResponse(responseCode = "400", description = "Invalid or empty query")
    @APIResponse(responseCode = "500", description = "Internal server error")
    @GET
    @Path("/search")
    public List<OrderDto> search(@NotNull @QueryParam("q") String query) {
        return orderMapper.toOrderDtos(orderService.search(query));
    }
}
