name: Angular CI

on: [ push ]

jobs:
  build-gui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './gui/package-lock.json'
      - name: Install dependencies
        working-directory: ./gui
        run: npm ci
      - name: Build Angular app
        working-directory: ./gui
        run: npm run build
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: ./gui
          args: >
            -Dsonar.projectKey=alexandre-touret_feature-flag-workshop
            -Dsonar.organization=touretinfo
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
